export const styless: { [key: string]: React.CSSProperties } = {
  layout: {
    height: "100vh",
    backgroundImage: `url("https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAxNzA1MTlfMjU3%2FMDAxNDk1MTk4NTUwMTY0.KpDvMV5SxuAfsEVI80tH-FkdkWRKntXe4CxOut2171Ag.DnlLmpL7wTBXukwAv-J2IjHkmY1G2uZ4ivwNUH0CNuEg.JPEG.wsxdsa123%2Fcropped-1920-1080-832372.jpg&type=sc960_832")`,
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
  },
  container: {
    width: "300px",
    margin: "20px auto",
    textAlign: "center",
    borderRadius: "10px",
    boxShadow: "rgba(0, 0, 0, 0.24) 0px 3px 8px",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    padding: "20px",
  },
  input: {
    padding: "8px",
    width: "200px",
    marginRight: "5px",
    borderRadius: "5px",
    border: "1px solid #ccc",
  },
  addButton: {
    padding: "8px",
    cursor: "pointer",
    borderRadius: "5px",
    backgroundColor: "skyblue",
    color: "white",
    border: "none",
  },
  deleteAllButton: {
    padding: "8px",
    cursor: "pointer",
    borderRadius: "5px",
    backgroundColor: "skyblue",
    color: "white",
    border: "none",
    marginLeft: "10px",
    marginTop: "10px",
  },
  list: {
    listStyle: "none",
    padding: 0,
    fontSize: "15px",
  },
  item: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    margin: "5px 0",
    padding: "5px",
    borderBottom: "1px solid #ddd",
  },
  deleteButton: {
    background: "red",
    color: "white",
    border: "none",
    cursor: "pointer",
    padding: "5px",
    borderRadius: "5px",
  },
  completed: {
    textDecoration: "line-through",
    color: "gray",
  },
};
